# vermos-server

# Dockerised version of VERMOS

#FROM node:boron
#FROM node:carbon
FROM node:10-stretch

RUN apt-get update && apt-get install -y \
  build-essential \
  libssl-dev \
  dos2unix \
  wget \
  gzip \
  openssh-server \
  curl \
  python-minimal \
  libelf1 \
  locate \
  nano 

# Create app directory
RUN mkdir -p /opt/vermos
WORKDIR /opt/vermos

COPY install_yottadb.sh /opt/vermos
COPY gde.txt /opt/vermos
RUN chmod +x /opt/vermos/install_yottadb.sh

RUN cd /opt/vermos

# Install app dependencies
COPY package.json /opt/vermos
RUN npm install
RUN npm install module-exists

# Install YottaDB & NodeM

RUN ["/opt/vermos/install_yottadb.sh"]

# Bundle app source
COPY . /opt/vermos

RUN chmod +x /opt/vermos/ydb

RUN mkdir /opt/vermos/www
RUN mkdir /opt/vermos/www/vermos-monitor

RUN cp /opt/vermos/node_modules/vermos-monitor/www/bundle.js /opt/vermos/www/vermos-monitor
RUN cp /opt/vermos/node_modules/vermos-monitor/www/*.html /opt/vermos/www/vermos-monitor
RUN cp /opt/vermos/node_modules/vermos-monitor/www/*.css /opt/vermos/www/vermos-monitor

RUN cp /opt/vermos/node_modules/ewd-client/lib/proto/ewd-client.js /opt/vermos/www

RUN cd /opt/vermos

EXPOSE 8080

# ENTRYPOINT ["/bin/bash", "-l"]

CMD [ "npm", "start" ]
